org: mateoismael
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30

  # Rol preexistente
  iam:
    role: arn:aws:iam::111097882274:role/LabRole

  # Variables de entorno
  environment:
    # (Opcional, si sigues usando DynamoDB en otros handlers)
    TABLE_NAME: ${sls:stage}-t_comentarios
    # Para Ingesta Push a S3
    BUCKET_NAME: ${self:service}-ingestion-${self:provider.stage}

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: comentario
          method: post

resources:
  Resources:
    # 1) Bucket S3 de ingesta (uno distinto por stage)
    IngestionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-ingestion-${self:provider.stage}

    # 2) Política inline para LabRole que permite hacer PutObject en ese bucket
    LabRoleS3PutPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: AllowS3PutIngestion
        Roles:
          - LabRole
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::${self:service}-ingestion-${self:provider.stage}/*
