service: api-comentario

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}                    # <— Aquí defines tu stage por defecto
  role: arn:aws:iam::111097882274:role/LabRole  # tu rol preexistente

  memorySize: 1024
  timeout: 30

  environment:
    # ahora sí existe provider.stage
    BUCKET_NAME: ${self:service}-ingestion-${self:provider.stage}
    TABLE_NAME:  ${self:provider.stage}-t_comentarios

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: comentario
          method: post

resources:
  Resources:
    IngestionBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-ingestion-${self:provider.stage}

    LabRoleS3PutPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: AllowS3PutIngestion
        Roles:
          - LabRole
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::${self:service}-ingestion-${self:provider.stage}/*
