org: mateoismael
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}                     # valor por defecto si no pasas --stage
  memorySize: 1024
  timeout: 29                                    # API Gateway máximo 29 s
  iam:
    role: arn:aws:iam::111097882274:role/LabRole # tu rol preexistente

  environment:
    TABLE_NAME: ${self:provider.stage}-t_comentarios
    BUCKET_NAME: ${self:service}-ingestion-${self:provider.stage}

functions:
  crear:
    handler: comentario.lambda_handler
    timeout: 29
    events:
      - http:
          path: comentario
          method: post

resources:
  Resources:
    # Bucket S3 de ingesta (uno por stage)
    IngestionBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-ingestion-${self:provider.stage}

    # Inline policy para que LabRole pueda subir objetos a ese bucket
    LabRoleS3PutPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: AllowS3PutIngestion
        Roles:
          - LabRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - arn:aws:s3:::${self:service}-ingestion-${self:provider.stage}/*
