org: mateoismael
service: api-comentario

provider:
  name: aws
  # 1) Agrego región (puedes cambiar 'us-east-1' por la que uses)
  region: ${opt:region, 'us-east-1'}
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    # 3) Usas tu rol existente
    role: arn:aws:iam::111097882274:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_comentarios
    # 2) Nueva variable para el bucket
    BUCKET_NAME: s11ingest-${sls:stage}

functions:
  crear:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario/crear
          method: post
          cors: true
          integration: lambda

resources:
  Resources:
    TablaComentarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # 3) Recurso para crear el bucket de ingesta por stage
    BucketIngesta:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
