org: mateoismael
service: api-comentario

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}         # default si no pasas --stage
  memorySize: 1024
  timeout: 29                        # <=29s para API Gateway

  # Serverless crear치 un IAM Role autom치ticamente 
  # y a ese le a침adir치 estas declaraciones de permiso:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:service}-ingestion-${self:provider.stage}/*

  environment:
    TABLE_NAME: ${self:provider.stage}-t_comentarios
    BUCKET_NAME: ${self:service}-ingestion-${self:provider.stage}

functions:
  crear:
    handler: comentario.lambda_handler
    timeout: 29
    events:
      - http:
          path: comentario
          method: post

resources:
  Resources:
    # Bucket S3 de ingesta, uno por stage
    IngestionBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:service}-ingestion-${self:provider.stage}

    # (Si sigues usando DynamoDB en otros handlers)
    ComentariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
